version: '2'
services:
 mysql:
  image: mysql:latest
  ports:
   - "3306:3306"
  container_name: mysql-docker
  network_mode: host
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: moviedb
   MYSQL_PASSWORD: root
   
 user-app:
  image: user-app
  build: movieauthentication/
  restart: always
  network_mode: host
  container_name: auth-docker
  depends_on:
   - mysql
  ports:
   - 8082:8082
  expose: [8082]

 spring:
  image: spring
  build: movieservice/
  restart: always
  network_mode: host
  container_name: spring-docker
  depends_on:
   - mysql
  ports:
   - 8080:8080
  expose: [8080]

 angular:
  image: angular-app
  build: frontend/
  network_mode: host
  container_name: angular-docker
  ports:
   - 4200:4200
