spring:
 datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: ${MYSQL_CI_URL}
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
 jpa:
  database-platform: ${MYSQL_DIALECT}
  hibernate:
   ddl-auto: update
  show-sql: true
server:
 port: 8080